export const data = [
  {
    id: 1457,
    type: "event",
    title: { rendered: "Bible and Beach" },
    acf: {
      content: [
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-calendar" aria-hidden="true"></i>',
            enabled: true,
            label: "Schedule",
            type: "schedule",
          },
          slug: "schedule",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: {
            title: "Schedule",
            days: [
              {
                day: [
                  {
                    name: "Breakfast",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-star" aria-hidden="true"></i>',
                    time: "12:00 am",
                    color: [
                      {
                        ID: 185,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:07",
                        post_date_gmt: "2022-12-01 19:19:07",
                        post_content: "",
                        post_title: "Blue",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "blue",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:54",
                        post_modified_gmt: "2023-04-11 21:05:54",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=185",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Lunch",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-star" aria-hidden="true"></i>',
                    time: "2:00 am",
                    color: [
                      {
                        ID: 187,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:45",
                        post_date_gmt: "2022-12-01 19:19:45",
                        post_content: "",
                        post_title: "Green",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "green",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:31",
                        post_modified_gmt: "2023-04-11 21:05:31",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=187",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-globe-stand" aria-hidden="true"></i>',
                    time: "4:00 am",
                    color: [
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                ],
              },
              {
                day: [
                  {
                    name: "Breakfast",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-microphone-stand" aria-hidden="true"></i>',
                    time: "1:00 am",
                    color: false,
                  },
                  {
                    name: "Lunch",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "1:30 am",
                    color: [
                      {
                        ID: 998,
                        post_author: "2",
                        post_date: "2023-06-07 15:28:42",
                        post_date_gmt: "2023-06-07 15:28:42",
                        post_content: "",
                        post_title: "Pink",
                        post_excerpt: "#0071bc",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "pink",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-10-29 02:35:00",
                        post_modified_gmt: "2023-10-29 02:35:00",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=998",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 575,
                        post_author: "2",
                        post_date: "2023-04-11 21:05:05",
                        post_date_gmt: "2023-04-11 21:05:05",
                        post_content: "",
                        post_title: "Purple",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "purple",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:05",
                        post_modified_gmt: "2023-04-11 21:05:05",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=575",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Main Hall",
                    icon: '<i class="fa-solid fa-couch" aria-hidden="true"></i>',
                    time: "",
                    color: false,
                  },
                ],
              },
            ],
          },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-phone" aria-hidden="true"></i>',
            enabled: true,
            label: "Event Contacts",
            type: "contacts",
          },
          slug: "event-contacts",
          menu: { title: "", description: "", buttons: false },
          contacts: {
            title: "Event Contacts",
            description: "<p>Have an emergency. Let us know.</p>\n",
            contacts: [
              {
                image: {
                  ID: 1398,
                  id: 1398,
                  title: "DSCF3858",
                  filename: "DSCF3858-scaled.jpg",
                  filesize: 569102,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-scaled.jpg",
                  link: "http://ciy-companion.local/event/mov23ire/dscf3858/",
                  alt: "",
                  author: "29",
                  description: "",
                  caption: "",
                  name: "dscf3858",
                  status: "inherit",
                  uploaded_to: 1360,
                  date: "2023-07-28 11:43:16",
                  modified: "2023-07-28 11:43:16",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 1707,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-150x150.jpg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-200x300.jpg",
                    "medium-width": 200,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-768x1152.jpg",
                    "medium_large-width": 768,
                    "medium_large-height": 1152,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-683x1024.jpg",
                    "large-width": 683,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1024x1536.jpg",
                    "1536x1536-width": 1024,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1365x2048.jpg",
                    "2048x2048-width": 1365,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Jimmy",
                role: "Director",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: {
                  ID: 1413,
                  id: 1413,
                  title: "NFW STAFF",
                  filename: "anthony_morgan_square-150x150-1.jpeg",
                  filesize: 16721,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                  link: "http://ciy-companion.local/?attachment_id=1413",
                  alt: "",
                  author: "26",
                  description: "",
                  caption: "",
                  name: "nfw-staff-2",
                  status: "inherit",
                  uploaded_to: 749,
                  date: "2023-07-31 16:47:25",
                  modified: "2023-07-31 16:47:25",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 150,
                  height: 150,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "medium-width": 150,
                    "medium-height": 150,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "medium_large-width": 150,
                    "medium_large-height": 150,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "large-width": 150,
                    "large-height": 150,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "1536x1536-width": 150,
                    "1536x1536-height": 150,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "2048x2048-width": 150,
                    "2048x2048-height": 150,
                  },
                },
                name: "Bill",
                role: "Assist. Director",
                email: "",
                phone: "555-555-1234",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: {
                  ID: 1238,
                  id: 1238,
                  title: "Mallory Contact Picture",
                  filename: "Mallory-Contact-Picture.jpeg",
                  filesize: 865740,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture.jpeg",
                  link: "http://ciy-companion.local/?attachment_id=1238",
                  alt: "",
                  author: "26",
                  description: "",
                  caption: "",
                  name: "mallory-contact-picture",
                  status: "inherit",
                  uploaded_to: 596,
                  date: "2023-07-05 15:26:38",
                  modified: "2023-07-05 15:26:38",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 2560,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-150x150.jpeg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-300x300.jpeg",
                    "medium-width": 300,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-768x768.jpeg",
                    "medium_large-width": 768,
                    "medium_large-height": 768,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-1024x1024.jpeg",
                    "large-width": 1024,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-1536x1536.jpeg",
                    "1536x1536-width": 1536,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-2048x2048.jpeg",
                    "2048x2048-width": 2048,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Susan",
                role: "Her role is realy long and may need more space",
                email: "susan@ciy.com",
                phone: "555-555-5555",
                url: "https://ciy.com",
                city: "Louisville",
                state: "KY",
                description: "<p>Here is a BIO for Susan.</p>\n",
              },
              {
                image: {
                  ID: 1397,
                  id: 1397,
                  title: "DSCF3806",
                  filename: "DSCF3806-scaled.jpg",
                  filesize: 558701,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-scaled.jpg",
                  link: "http://ciy-companion.local/event/mov23ire/dscf3806/",
                  alt: "",
                  author: "29",
                  description: "",
                  caption: "",
                  name: "dscf3806",
                  status: "inherit",
                  uploaded_to: 1360,
                  date: "2023-07-28 11:41:59",
                  modified: "2023-07-28 11:41:59",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 1707,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-150x150.jpg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-200x300.jpg",
                    "medium-width": 200,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-768x1152.jpg",
                    "medium_large-width": 768,
                    "medium_large-height": 1152,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-683x1024.jpg",
                    "large-width": 683,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1024x1536.jpg",
                    "1536x1536-width": 1024,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1365x2048.jpg",
                    "2048x2048-width": 1365,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Jill",
                role: "",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: false,
                name: "Max",
                role: "no image",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
            ],
          },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: {
            title: "Schedule",
            days: [
              {
                day: [
                  {
                    name: "Breakfast",
                    location: "Main Hall",
                    icon: "",
                    time: "12:00 am",
                    color: [
                      {
                        ID: 185,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:07",
                        post_date_gmt: "2022-12-01 19:19:07",
                        post_content: "",
                        post_title: "Blue",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "blue",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:54",
                        post_modified_gmt: "2023-04-11 21:05:54",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=185",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Lunch",
                    location: "Main Hall",
                    icon: "",
                    time: "2:00 am",
                    color: [
                      {
                        ID: 187,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:45",
                        post_date_gmt: "2022-12-01 19:19:45",
                        post_content: "",
                        post_title: "Green",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "green",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:31",
                        post_modified_gmt: "2023-04-11 21:05:31",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=187",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Main Hall",
                    icon: "",
                    time: "4:00 am",
                    color: [
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                ],
              },
              {
                day: [
                  {
                    name: "Breakfast",
                    location: "Main Hall",
                    icon: "",
                    time: "1:00 am",
                    color: false,
                  },
                  {
                    name: "Lunch",
                    location: "Main Hall",
                    icon: "",
                    time: "1:30 am",
                    color: [
                      {
                        ID: 998,
                        post_author: "2",
                        post_date: "2023-06-07 15:28:42",
                        post_date_gmt: "2023-06-07 15:28:42",
                        post_content: "",
                        post_title: "Pink",
                        post_excerpt: "#0071bc",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "pink",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-10-29 02:35:00",
                        post_modified_gmt: "2023-10-29 02:35:00",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=998",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 575,
                        post_author: "2",
                        post_date: "2023-04-11 21:05:05",
                        post_date_gmt: "2023-04-11 21:05:05",
                        post_content: "",
                        post_title: "Purple",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "purple",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:05",
                        post_modified_gmt: "2023-04-11 21:05:05",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=575",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Main Hall",
                    icon: "",
                    time: "",
                    color: false,
                  },
                ],
              },
            ],
          },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-book-open" aria-hidden="true"></i>',
            enabled: true,
            label: "External Store",
            type: "external",
          },
          slug: "store",
          menu: { title: "", description: "", buttons: false },
          contacts: {
            title: "Staff Contacts",
            description: "<p>Have an emergency. Let us know.</p>\n",
            contacts: [
              {
                image: {
                  ID: 1398,
                  id: 1398,
                  title: "DSCF3858",
                  filename: "DSCF3858-scaled.jpg",
                  filesize: 569102,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-scaled.jpg",
                  link: "http://ciy-companion.local/event/mov23ire/dscf3858/",
                  alt: "",
                  author: "29",
                  description: "",
                  caption: "",
                  name: "dscf3858",
                  status: "inherit",
                  uploaded_to: 1360,
                  date: "2023-07-28 11:43:16",
                  modified: "2023-07-28 11:43:16",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 1707,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-150x150.jpg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-200x300.jpg",
                    "medium-width": 200,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-768x1152.jpg",
                    "medium_large-width": 768,
                    "medium_large-height": 1152,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-683x1024.jpg",
                    "large-width": 683,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1024x1536.jpg",
                    "1536x1536-width": 1024,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1365x2048.jpg",
                    "2048x2048-width": 1365,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Jimmy",
                role: "Director",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: {
                  ID: 1413,
                  id: 1413,
                  title: "NFW STAFF",
                  filename: "anthony_morgan_square-150x150-1.jpeg",
                  filesize: 16721,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                  link: "http://ciy-companion.local/?attachment_id=1413",
                  alt: "",
                  author: "26",
                  description: "",
                  caption: "",
                  name: "nfw-staff-2",
                  status: "inherit",
                  uploaded_to: 749,
                  date: "2023-07-31 16:47:25",
                  modified: "2023-07-31 16:47:25",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 150,
                  height: 150,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "medium-width": 150,
                    "medium-height": 150,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "medium_large-width": 150,
                    "medium_large-height": 150,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "large-width": 150,
                    "large-height": 150,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "1536x1536-width": 150,
                    "1536x1536-height": 150,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                    "2048x2048-width": 150,
                    "2048x2048-height": 150,
                  },
                },
                name: "Bill",
                role: "Assist. Director",
                email: "",
                phone: "555-555-1234",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: {
                  ID: 1238,
                  id: 1238,
                  title: "Mallory Contact Picture",
                  filename: "Mallory-Contact-Picture.jpeg",
                  filesize: 865740,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture.jpeg",
                  link: "http://ciy-companion.local/?attachment_id=1238",
                  alt: "",
                  author: "26",
                  description: "",
                  caption: "",
                  name: "mallory-contact-picture",
                  status: "inherit",
                  uploaded_to: 596,
                  date: "2023-07-05 15:26:38",
                  modified: "2023-07-05 15:26:38",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 2560,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-150x150.jpeg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-300x300.jpeg",
                    "medium-width": 300,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-768x768.jpeg",
                    "medium_large-width": 768,
                    "medium_large-height": 768,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-1024x1024.jpeg",
                    "large-width": 1024,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-1536x1536.jpeg",
                    "1536x1536-width": 1536,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/04/Mallory-Contact-Picture-2048x2048.jpeg",
                    "2048x2048-width": 2048,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Susan",
                role: "Her role is realy long and may need more space",
                email: "susan@ciy.com",
                phone: "555-555-5555",
                url: "https://ciy.com",
                city: "Louisville",
                state: "KY",
                description: "<p>Here is a BIO for Susan.</p>\n",
              },
              {
                image: {
                  ID: 1397,
                  id: 1397,
                  title: "DSCF3806",
                  filename: "DSCF3806-scaled.jpg",
                  filesize: 558701,
                  url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-scaled.jpg",
                  link: "http://ciy-companion.local/event/mov23ire/dscf3806/",
                  alt: "",
                  author: "29",
                  description: "",
                  caption: "",
                  name: "dscf3806",
                  status: "inherit",
                  uploaded_to: 1360,
                  date: "2023-07-28 11:41:59",
                  modified: "2023-07-28 11:41:59",
                  menu_order: 0,
                  mime_type: "image/jpeg",
                  type: "image",
                  subtype: "jpeg",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 1707,
                  height: 2560,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-150x150.jpg",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-200x300.jpg",
                    "medium-width": 200,
                    "medium-height": 300,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-768x1152.jpg",
                    "medium_large-width": 768,
                    "medium_large-height": 1152,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-683x1024.jpg",
                    "large-width": 683,
                    "large-height": 1024,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1024x1536.jpg",
                    "1536x1536-width": 1024,
                    "1536x1536-height": 1536,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1365x2048.jpg",
                    "2048x2048-width": 1365,
                    "2048x2048-height": 2048,
                  },
                },
                name: "Jill",
                role: "",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
              {
                image: false,
                name: "Max",
                role: "no image",
                email: "",
                phone: "555-555-5555",
                url: "",
                city: "",
                state: "",
                description: "",
              },
            ],
          },
          embedded: { title: "", url: "" },
          external: { url: "https://ciy.com" },
          schedule: { title: "", days: false },
          connect: {
            title: "Connect with us",
            connections: [
              {
                title: "Spotify",
                icon: '<i class="fa-brands fa-spotify" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
              {
                title: "Facebook",
                icon: '<i class="fa-brands fa-facebook" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
            ],
          },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-globe-stand" aria-hidden="true"></i>',
            enabled: true,
            label: "CIY",
            type: "embedded",
          },
          slug: "ciy",
          menu: {
            title: "Where the River Divides",
            description:
              "<p>Where the river divides needs some content here.</p>\n",
            buttons: [
              {
                slug: "",
                enabled: true,
                content: {
                  label: "",
                  type: "url",
                  url: "https://ciy.com",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: { title: "", image: false },
                },
              },
              {
                slug: "",
                enabled: true,
                content: {
                  label: "",
                  type: "embedded",
                  url: "",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "CIY", url: "https://ciy.com" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: { title: "", image: false },
                },
              },
              {
                slug: "",
                enabled: true,
                content: {
                  label: "",
                  type: "connection",
                  url: "",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: {
                    title: "Connect with us",
                    connections: [
                      {
                        title: "Podcast",
                        icon: '<i class="fa-solid fa-microphone-stand" aria-hidden="true"></i>',
                        url: "https://ciy.com",
                      },
                      {
                        title: "Instagram",
                        icon: '<i class="fa-solid fa-film" aria-hidden="true"></i>',
                        url: "https://ciy.com",
                      },
                    ],
                  },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: { title: "", image: false },
                },
              },
            ],
          },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "CIY Webpage", url: "https://ciy.com" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: {
            title: "Connect with us",
            connections: [
              {
                title: "Spotify",
                icon: '<i class="fa-brands fa-spotify" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
              {
                title: "Facebook",
                icon: '<i class="fa-brands fa-facebook" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
            ],
          },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-duotone fa-star" aria-hidden="true"></i>',
            enabled: true,
            label: "Connect",
            type: "connect",
          },
          slug: "connect",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "https://ciy.com" },
          schedule: { title: "", days: false },
          connect: {
            title: "Connect with Us",
            connections: [
              {
                title: "Facebook",
                icon: '<i class="fa-brands fa-facebook" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
              {
                title: "TikTok",
                icon: '<i class="fa-brands fa-tiktok" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
              {
                title: "Spotify",
                icon: '<i class="fa-brands fa-spotify" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
              {
                title: "YouTube",
                icon: '<i class="fa-brands fa-youtube" aria-hidden="true"></i>',
                url: "https://ciy.com",
              },
            ],
          },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-film" aria-hidden="true"></i>',
            enabled: true,
            label: "Video",
            type: "video",
          },
          slug: "video",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "CIY", url: "https://ciy.com" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: { title: "", connections: false },
          video: { title: "Leader Video", id: "84978993" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-map" aria-hidden="true"></i>',
            enabled: true,
            label: "Campus Map",
            type: "image",
          },
          slug: "campus-map",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: { title: "", connections: false },
          video: { title: "Watch This forst", id: "84978993" },
          image: {
            title: "Campus Map",
            image:
              "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark-Campus-Map-1.jpg",
          },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-arrows-split-up-and-left" aria-hidden="true"></i>',
            enabled: true,
            label: "Where the River Divides",
            type: "menu",
          },
          slug: "where-the-river-divides",
          menu: {
            title: "Where the River Divides",
            description:
              "<p>Here is some interesting things you need to know about Where the River Divides. Check out the links below for more information.</p>\n",
            buttons: [
              {
                slug: "external-link",
                enabled: true,
                content: {
                  label: "Go to CIY",
                  type: "url",
                  url: "https://ciy.com",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: { title: "", image: false },
                },
              },
              {
                slug: "trailer",
                enabled: true,
                content: {
                  label: "Trailer",
                  type: "video",
                  url: "",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "Trailer", id: "84978993" },
                  image: { title: "", image: false },
                },
              },
              {
                slug: "leaders",
                enabled: true,
                content: {
                  label: "Leaders",
                  type: "contacts",
                  url: "",
                  contacts: {
                    title: "Leaders",
                    description: "<p>Find your leader here.</p>\n",
                    contacts: [
                      {
                        image: {
                          ID: 1413,
                          id: 1413,
                          title: "NFW STAFF",
                          filename: "anthony_morgan_square-150x150-1.jpeg",
                          filesize: 16721,
                          url: "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                          link: "http://ciy-companion.local/?attachment_id=1413",
                          alt: "",
                          author: "26",
                          description: "",
                          caption: "",
                          name: "nfw-staff-2",
                          status: "inherit",
                          uploaded_to: 749,
                          date: "2023-07-31 16:47:25",
                          modified: "2023-07-31 16:47:25",
                          menu_order: 0,
                          mime_type: "image/jpeg",
                          type: "image",
                          subtype: "jpeg",
                          icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                          width: 150,
                          height: 150,
                          sizes: {
                            thumbnail:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "thumbnail-width": 150,
                            "thumbnail-height": 150,
                            medium:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "medium-width": 150,
                            "medium-height": 150,
                            medium_large:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "medium_large-width": 150,
                            "medium_large-height": 150,
                            large:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "large-width": 150,
                            "large-height": 150,
                            "1536x1536":
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "1536x1536-width": 150,
                            "1536x1536-height": 150,
                            "2048x2048":
                              "http://ciy-companion.local/wp-content/uploads/2023/05/anthony_morgan_square-150x150-1.jpeg",
                            "2048x2048-width": 150,
                            "2048x2048-height": 150,
                          },
                        },
                        name: "Adam",
                        role: "Director",
                        email: "adam@ciy.com",
                        phone: "555-555-5555",
                        url: "",
                        city: "",
                        state: "",
                        description: "",
                      },
                      {
                        image: {
                          ID: 1398,
                          id: 1398,
                          title: "DSCF3858",
                          filename: "DSCF3858-scaled.jpg",
                          filesize: 569102,
                          url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-scaled.jpg",
                          link: "http://ciy-companion.local/event/mov23ire/dscf3858/",
                          alt: "",
                          author: "29",
                          description: "",
                          caption: "",
                          name: "dscf3858",
                          status: "inherit",
                          uploaded_to: 1360,
                          date: "2023-07-28 11:43:16",
                          modified: "2023-07-28 11:43:16",
                          menu_order: 0,
                          mime_type: "image/jpeg",
                          type: "image",
                          subtype: "jpeg",
                          icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                          width: 1707,
                          height: 2560,
                          sizes: {
                            thumbnail:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-150x150.jpg",
                            "thumbnail-width": 150,
                            "thumbnail-height": 150,
                            medium:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-200x300.jpg",
                            "medium-width": 200,
                            "medium-height": 300,
                            medium_large:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-768x1152.jpg",
                            "medium_large-width": 768,
                            "medium_large-height": 1152,
                            large:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-683x1024.jpg",
                            "large-width": 683,
                            "large-height": 1024,
                            "1536x1536":
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1024x1536.jpg",
                            "1536x1536-width": 1024,
                            "1536x1536-height": 1536,
                            "2048x2048":
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3858-1365x2048.jpg",
                            "2048x2048-width": 1365,
                            "2048x2048-height": 2048,
                          },
                        },
                        name: "Bob",
                        role: "Assistant Director",
                        email: "bob@ciy.com",
                        phone: "555-555-5555",
                        url: "",
                        city: "",
                        state: "",
                        description: "",
                      },
                      {
                        image: {
                          ID: 1397,
                          id: 1397,
                          title: "DSCF3806",
                          filename: "DSCF3806-scaled.jpg",
                          filesize: 558701,
                          url: "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-scaled.jpg",
                          link: "http://ciy-companion.local/event/mov23ire/dscf3806/",
                          alt: "",
                          author: "29",
                          description: "",
                          caption: "",
                          name: "dscf3806",
                          status: "inherit",
                          uploaded_to: 1360,
                          date: "2023-07-28 11:41:59",
                          modified: "2023-07-28 11:41:59",
                          menu_order: 0,
                          mime_type: "image/jpeg",
                          type: "image",
                          subtype: "jpeg",
                          icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                          width: 1707,
                          height: 2560,
                          sizes: {
                            thumbnail:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-150x150.jpg",
                            "thumbnail-width": 150,
                            "thumbnail-height": 150,
                            medium:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-200x300.jpg",
                            "medium-width": 200,
                            "medium-height": 300,
                            medium_large:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-768x1152.jpg",
                            "medium_large-width": 768,
                            "medium_large-height": 1152,
                            large:
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-683x1024.jpg",
                            "large-width": 683,
                            "large-height": 1024,
                            "1536x1536":
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1024x1536.jpg",
                            "1536x1536-width": 1024,
                            "1536x1536-height": 1536,
                            "2048x2048":
                              "http://ciy-companion.local/wp-content/uploads/2023/07/DSCF3806-1365x2048.jpg",
                            "2048x2048-width": 1365,
                            "2048x2048-height": 2048,
                          },
                        },
                        name: "Christy",
                        role: "Administration",
                        email: "christy@ciy.com",
                        phone: "555-555-5555",
                        url: "",
                        city: "",
                        state: "",
                        description: "",
                      },
                      {
                        image: {
                          ID: 1328,
                          id: 1328,
                          title: "Your profile picture",
                          filename: "Your-profile-picture.jpeg",
                          filesize: 39580,
                          url: "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture.jpeg",
                          link: "http://ciy-companion.local/?attachment_id=1328",
                          alt: "",
                          author: "24",
                          description: "",
                          caption: "",
                          name: "your-profile-picture",
                          status: "inherit",
                          uploaded_to: 923,
                          date: "2023-07-17 14:37:24",
                          modified: "2023-07-17 14:37:24",
                          menu_order: 0,
                          mime_type: "image/jpeg",
                          type: "image",
                          subtype: "jpeg",
                          icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                          width: 576,
                          height: 576,
                          sizes: {
                            thumbnail:
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture-150x150.jpeg",
                            "thumbnail-width": 150,
                            "thumbnail-height": 150,
                            medium:
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture-300x300.jpeg",
                            "medium-width": 300,
                            "medium-height": 300,
                            medium_large:
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture.jpeg",
                            "medium_large-width": 576,
                            "medium_large-height": 576,
                            large:
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture.jpeg",
                            "large-width": 576,
                            "large-height": 576,
                            "1536x1536":
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture.jpeg",
                            "1536x1536-width": 576,
                            "1536x1536-height": 576,
                            "2048x2048":
                              "http://ciy-companion.local/wp-content/uploads/2023/06/Your-profile-picture.jpeg",
                            "2048x2048-width": 576,
                            "2048x2048-height": 576,
                          },
                        },
                        name: "Dylan",
                        role: "Intern",
                        email: "",
                        phone: "",
                        url: "",
                        city: "",
                        state: "",
                        description: "",
                      },
                      {
                        image: false,
                        name: "Erik",
                        role: "Nurse",
                        email: "",
                        phone: "",
                        url: "",
                        city: "Louisville",
                        state: "KY",
                        description: "",
                      },
                      {
                        image: {
                          ID: 1285,
                          id: 1285,
                          title: "IMG_2588_Original",
                          filename: "IMG_2588_Original.png",
                          filesize: 8954818,
                          url: "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original.png",
                          link: "http://ciy-companion.local/?attachment_id=1285",
                          alt: "",
                          author: "2",
                          description: "",
                          caption: "",
                          name: "img_2588_original",
                          status: "inherit",
                          uploaded_to: 855,
                          date: "2023-07-11 00:15:10",
                          modified: "2023-07-11 00:15:10",
                          menu_order: 0,
                          mime_type: "image/png",
                          type: "image",
                          subtype: "png",
                          icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                          width: 3200,
                          height: 3200,
                          sizes: {
                            thumbnail:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-150x150.png",
                            "thumbnail-width": 150,
                            "thumbnail-height": 150,
                            medium:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-300x300.png",
                            "medium-width": 300,
                            "medium-height": 300,
                            medium_large:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-768x768.png",
                            "medium_large-width": 768,
                            "medium_large-height": 768,
                            large:
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-1024x1024.png",
                            "large-width": 1024,
                            "large-height": 1024,
                            "1536x1536":
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-1536x1536.png",
                            "1536x1536-width": 1536,
                            "1536x1536-height": 1536,
                            "2048x2048":
                              "http://ciy-companion.local/wp-content/uploads/2023/05/IMG_2588_Original-2048x2048.png",
                            "2048x2048-width": 2048,
                            "2048x2048-height": 2048,
                          },
                        },
                        name: "Frank",
                        role: "",
                        email: "",
                        phone: "",
                        url: "https://ciy.com",
                        city: "",
                        state: "",
                        description: "<p>Frank has three dogs.</p>\n",
                      },
                    ],
                  },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: { title: "", image: false },
                },
              },
              {
                slug: "seating-chart",
                enabled: true,
                content: {
                  label: "Seating Chart",
                  type: "image",
                  url: "",
                  contacts: { title: "", description: "", contacts: false },
                  menu: { title: "", description: "", buttons: false },
                  embedded: { title: "", url: "" },
                  connection: { title: "", connections: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                  image: {
                    title: "Tuesday Seating",
                    image:
                      "http://ciy-companion.local/wp-content/uploads/2023/05/CO-Seating-Chart-N3-_-M4-.jpg",
                  },
                },
              },
            ],
          },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-couch" aria-hidden="true"></i>',
            enabled: true,
            label: "College Partners",
            type: "grid",
          },
          slug: "college",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: {
            title: "College Partners",
            description: "<p>We&#8217;d like to thank these partners</p>\n",
            images: [
              {
                image: {
                  ID: 767,
                  id: 767,
                  title: "KCU Knight and Name Stack (1)",
                  filename: "KCU-Knight-and-Name-Stack-1.png",
                  filesize: 334737,
                  url: "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1.png",
                  link: "http://ciy-companion.local/?attachment_id=767",
                  alt: "",
                  author: "2",
                  description: "",
                  caption: "",
                  name: "kcu-knight-and-name-stack-1",
                  status: "inherit",
                  uploaded_to: 5,
                  date: "2023-05-17 19:40:50",
                  modified: "2023-05-17 19:40:50",
                  menu_order: 0,
                  mime_type: "image/png",
                  type: "image",
                  subtype: "png",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 4517,
                  height: 1819,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-150x150.png",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-300x121.png",
                    "medium-width": 300,
                    "medium-height": 121,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-768x309.png",
                    "medium_large-width": 768,
                    "medium_large-height": 309,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-1024x412.png",
                    "large-width": 1024,
                    "large-height": 412,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-1536x619.png",
                    "1536x1536-width": 1536,
                    "1536x1536-height": 619,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/KCU-Knight-and-Name-Stack-1-2048x825.png",
                    "2048x2048-width": 2048,
                    "2048x2048-height": 825,
                  },
                },
                label: "Kentucky Christian University",
                url: "https://ciy.com",
              },
              {
                image: {
                  ID: 753,
                  id: 753,
                  title: "Johnson-trasparent",
                  filename: "Johnson-trasparent.png",
                  filesize: 70015,
                  url: "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                  link: "http://ciy-companion.local/?attachment_id=753",
                  alt: "",
                  author: "2",
                  description: "",
                  caption: "",
                  name: "johnson-trasparent",
                  status: "inherit",
                  uploaded_to: 5,
                  date: "2023-05-10 16:50:10",
                  modified: "2023-05-10 16:50:10",
                  menu_order: 0,
                  mime_type: "image/png",
                  type: "image",
                  subtype: "png",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 3001,
                  height: 986,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "thumbnail-width": 150,
                    "thumbnail-height": 49,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "medium-width": 300,
                    "medium-height": 99,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "medium_large-width": 768,
                    "medium_large-height": 252,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "large-width": 1024,
                    "large-height": 336,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "1536x1536-width": 1536,
                    "1536x1536-height": 505,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Johnson-trasparent.png",
                    "2048x2048-width": 2048,
                    "2048x2048-height": 673,
                  },
                },
                label: "Johnson University",
                url: "https://ciy.com",
              },
              {
                image: {
                  ID: 751,
                  id: 751,
                  title: "Ozark_navy_transparent",
                  filename: "Ozark_navy_transparent-1.png",
                  filesize: 18913,
                  url: "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1.png",
                  link: "http://ciy-companion.local/?attachment_id=751",
                  alt: "",
                  author: "2",
                  description: "",
                  caption: "",
                  name: "ozark_navy_transparent",
                  status: "inherit",
                  uploaded_to: 5,
                  date: "2023-05-10 16:39:08",
                  modified: "2023-05-10 16:39:08",
                  menu_order: 0,
                  mime_type: "image/png",
                  type: "image",
                  subtype: "png",
                  icon: "http://ciy-companion.local/wp-includes/images/media/default.png",
                  width: 4116,
                  height: 1195,
                  sizes: {
                    thumbnail:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-150x150.png",
                    "thumbnail-width": 150,
                    "thumbnail-height": 150,
                    medium:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-300x87.png",
                    "medium-width": 300,
                    "medium-height": 87,
                    medium_large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-768x223.png",
                    "medium_large-width": 768,
                    "medium_large-height": 223,
                    large:
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-1024x297.png",
                    "large-width": 1024,
                    "large-height": 297,
                    "1536x1536":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-1536x446.png",
                    "1536x1536-width": 1536,
                    "1536x1536-height": 446,
                    "2048x2048":
                      "http://ciy-companion.local/wp-content/uploads/2022/11/Ozark_navy_transparent-1-2048x595.png",
                    "2048x2048-width": 2048,
                    "2048x2048-height": 595,
                  },
                },
                label: "Ozark Christian College",
                url: "https://ciy.com",
              },
            ],
          },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-comments" aria-hidden="true"></i>',
            enabled: true,
            label: "Convos",
            type: "app",
          },
          slug: "convos",
          menu: { title: "", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: { title: "", days: false },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "Convos",
            name: "Convos",
            apple_store_url: "https://ciy.com",
            google_play_store_url: "https://ciy.com",
            description: "<p>This is an app description</p>\n",
            icon: "http://ciy-companion.local/wp-content/uploads/2023/10/ConvosAppIcon.png",
          },
        },
      ],
      location: "Louisville, KY",
      start_date: "10/25/2023",
      end_date: "11/23/2023",
      coming_soon: false,
      coming_soon_data: {
        message: "<p>Stay tuned</p>\n",
        label: "Go to CIY",
        url: "https://ciy.com",
      },
    },
  },
];
