export const data = [
  {
    id: 1636,
    type: "event",
    title: { rendered: "NEW TN1" },
    acf: {
      content: [
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-bed" aria-hidden="true"></i>',
            enabled: true,
            label: "First Menu",
            type: "menu",
          },
          slug: "first-menu",
          menu: {
            title: "First Menu",
            description: "<p>Here is the first menu</p>\n",
            buttons: [
              {
                label: "External Link",
                slug: "external-link",
                type: "url",
                enabled: true,
                content: {
                  app: {
                    title: "",
                    name: "",
                    apple_store_url: "",
                    google_play_store_url: "",
                    description: "",
                    icon: false,
                  },
                  contacts: { title: "", description: "", contacts: false },
                  connection: { title: "", connections: false },
                  embedded: { title: "", url: "" },
                  external: { url: "https://ciy.com" },
                  grid: { title: "", description: "", images: false },
                  image: { title: "", image: false },
                  menu: { title: "", description: "", buttons: false },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                },
              },
              {
                label: "Sub Menu",
                slug: "sub-menu",
                type: "menu",
                enabled: true,
                content: {
                  app: {
                    title: "",
                    name: "",
                    apple_store_url: "",
                    google_play_store_url: "",
                    description: "",
                    icon: false,
                  },
                  contacts: { title: "", description: "", contacts: false },
                  connection: { title: "", connections: false },
                  embedded: { title: "", url: "" },
                  external: { url: "" },
                  grid: { title: "", description: "", images: false },
                  image: { title: "", image: false },
                  menu: {
                    title: "Sub Menu",
                    description: "",
                    buttons: [
                      {
                        label: "First Sub Item",
                        slug: "first-sub-item",
                        type: "embedded",
                        enabled: true,
                        content: {
                          app: {
                            title: "",
                            name: "",
                            apple_store_url: "",
                            google_play_store_url: "",
                            description: "",
                            icon: false,
                          },
                          contacts: {
                            title: "",
                            description: "",
                            contacts: false,
                          },
                          connection: { title: "", connections: false },
                          embedded: {
                            title: "External Link",
                            url: "https://ciy.com",
                          },
                          external: { url: "" },
                          grid: { title: "", description: "", images: false },
                          image: { title: "", image: false },
                          menu: { title: "", description: "", buttons: false },
                          schedule: { title: "", days: false },
                          video: { title: "", id: "" },
                        },
                      },
                      {
                        label: "Second Sub Item",
                        slug: "second-sub-item",
                        type: "menu",
                        enabled: true,
                        content: {
                          app: {
                            title: "",
                            name: "",
                            apple_store_url: "",
                            google_play_store_url: "",
                            description: "",
                            icon: false,
                          },
                          contacts: {
                            title: "",
                            description: "",
                            contacts: false,
                          },
                          connection: { title: "", connections: false },
                          embedded: { title: "", url: "" },
                          external: { url: "" },
                          grid: { title: "", description: "", images: false },
                          image: { title: "", image: false },
                          menu: {
                            title: "Sub Sub Menu",
                            description: "",
                            buttons: [
                              {
                                label: "Image",
                                slug: "image",
                                type: "image",
                                enabled: true,
                                content: {
                                  app: {
                                    title: "",
                                    name: "",
                                    apple_store_url: "",
                                    google_play_store_url: "",
                                    description: "",
                                    icon: false,
                                  },
                                  contacts: {
                                    title: "",
                                    description: "",
                                    contacts: false,
                                  },
                                  connection: { title: "", connections: false },
                                  embedded: { title: "", url: "" },
                                  external: { url: "" },
                                  grid: {
                                    title: "",
                                    description: "",
                                    images: false,
                                  },
                                  image: {
                                    title: "Image",
                                    image:
                                      "http://ciy-companion.local/wp-content/uploads/2023/05/CO-Seating-Chart-N3-_-M4-.jpg",
                                  },
                                  schedule: { title: "", days: false },
                                  video: { title: "", id: "" },
                                },
                              },
                            ],
                          },
                          schedule: { title: "", days: false },
                          video: { title: "", id: "" },
                        },
                      },
                    ],
                  },
                  schedule: { title: "", days: false },
                  video: { title: "", id: "" },
                },
              },
            ],
          },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: {
            title: "Schedule",
            days: [
              {
                day: [
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:00 pm",
                    color: [
                      {
                        ID: 187,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:45",
                        post_date_gmt: "2022-12-01 19:19:45",
                        post_content: "",
                        post_title: "Green",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "green",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:31",
                        post_modified_gmt: "2023-04-11 21:05:31",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=187",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 575,
                        post_author: "2",
                        post_date: "2023-04-11 21:05:05",
                        post_date_gmt: "2023-04-11 21:05:05",
                        post_content: "",
                        post_title: "Purple",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "purple",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:05",
                        post_modified_gmt: "2023-04-11 21:05:05",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=575",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:20 pm",
                    color: [
                      {
                        ID: 998,
                        post_author: "2",
                        post_date: "2023-06-07 15:28:42",
                        post_date_gmt: "2023-06-07 15:28:42",
                        post_content: "",
                        post_title: "Pink",
                        post_excerpt: "#0071bc",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "pink",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-10-29 02:35:00",
                        post_modified_gmt: "2023-10-29 02:35:00",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=998",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:40 pm",
                    color: [
                      {
                        ID: 185,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:07",
                        post_date_gmt: "2022-12-01 19:19:07",
                        post_content: "",
                        post_title: "Blue",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "blue",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:54",
                        post_modified_gmt: "2023-04-11 21:05:54",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=185",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 183,
                        post_author: "1",
                        post_date: "2022-12-01 19:15:27",
                        post_date_gmt: "2022-12-01 19:15:27",
                        post_content: "",
                        post_title: "Orange",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "orange",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:04:20",
                        post_modified_gmt: "2023-04-11 21:04:20",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=183",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "6:00 pm",
                    color: [
                      {
                        ID: 186,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:30",
                        post_date_gmt: "2022-12-01 19:19:30",
                        post_content: "",
                        post_title: "Yellow",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "yellow",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:19:30",
                        post_modified_gmt: "2022-12-01 19:19:30",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=186",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Adult Leader Meeting",
                    location: "Lower Seeger",
                    icon: '<i class="fa-solid fa-file" aria-hidden="true"></i>',
                    time: "6:15 pm",
                    color: false,
                  },
                  {
                    name: "Student Only Session (Sit in Groups)",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-place-of-worship" aria-hidden="true"></i>',
                    time: "6:15 pm",
                    color: false,
                  },
                  {
                    name: "Intermission",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-crown" aria-hidden="true"></i>',
                    time: "7:15 pm",
                    color: false,
                  },
                  {
                    name: "Evening Session",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-place-of-worship" aria-hidden="true"></i>',
                    time: "7:30 pm",
                    color: false,
                  },
                  {
                    name: "Youth Group Time",
                    location: "",
                    icon: '<i class="fa-solid fa-square-question" aria-hidden="true"></i>',
                    time: "9:00 pm",
                    color: false,
                  },
                  {
                    name: "Late Night Hang ($1 Canteen)",
                    location: "",
                    icon: '<i class="fa-solid fa-crown" aria-hidden="true"></i>',
                    time: "",
                    color: false,
                  },
                  {
                    name: "Dorms",
                    location: "",
                    icon: '<i class="fa-solid fa-bed" aria-hidden="true"></i>',
                    time: "",
                    color: false,
                  },
                ],
              },
            ],
          },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
        {
          data: {
            "": null,
            icon: '<i class="fa-solid fa-user-group" aria-hidden="true"></i>',
            enabled: true,
            label: "Second Menu",
            type: "menu",
          },
          slug: "leader-resources",
          menu: { title: "Leader Resources", description: "", buttons: false },
          contacts: { title: "", description: "", contacts: false },
          embedded: { title: "", url: "" },
          external: { url: "" },
          schedule: {
            title: "Schedule",
            days: [
              {
                day: [
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:00 pm",
                    color: [
                      {
                        ID: 187,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:45",
                        post_date_gmt: "2022-12-01 19:19:45",
                        post_content: "",
                        post_title: "Green",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "green",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:31",
                        post_modified_gmt: "2023-04-11 21:05:31",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=187",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 575,
                        post_author: "2",
                        post_date: "2023-04-11 21:05:05",
                        post_date_gmt: "2023-04-11 21:05:05",
                        post_content: "",
                        post_title: "Purple",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "purple",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:05",
                        post_modified_gmt: "2023-04-11 21:05:05",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=575",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 184,
                        post_author: "1",
                        post_date: "2022-12-01 19:18:34",
                        post_date_gmt: "2022-12-01 19:18:34",
                        post_content: "",
                        post_title: "Red",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "red",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:18:34",
                        post_modified_gmt: "2022-12-01 19:18:34",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=184",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:20 pm",
                    color: [
                      {
                        ID: 998,
                        post_author: "2",
                        post_date: "2023-06-07 15:28:42",
                        post_date_gmt: "2023-06-07 15:28:42",
                        post_content: "",
                        post_title: "Pink",
                        post_excerpt: "#0071bc",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "pink",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-10-29 02:35:00",
                        post_modified_gmt: "2023-10-29 02:35:00",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=998",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "5:40 pm",
                    color: [
                      {
                        ID: 185,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:07",
                        post_date_gmt: "2022-12-01 19:19:07",
                        post_content: "",
                        post_title: "Blue",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "blue",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:05:54",
                        post_modified_gmt: "2023-04-11 21:05:54",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=185",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                      {
                        ID: 183,
                        post_author: "1",
                        post_date: "2022-12-01 19:15:27",
                        post_date_gmt: "2022-12-01 19:15:27",
                        post_content: "",
                        post_title: "Orange",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "orange",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2023-04-11 21:04:20",
                        post_modified_gmt: "2023-04-11 21:04:20",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=183",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Dinner",
                    location: "Sutton Hall ",
                    icon: '<i class="fa-solid fa-fork" aria-hidden="true"></i>',
                    time: "6:00 pm",
                    color: [
                      {
                        ID: 186,
                        post_author: "1",
                        post_date: "2022-12-01 19:19:30",
                        post_date_gmt: "2022-12-01 19:19:30",
                        post_content: "",
                        post_title: "Yellow",
                        post_excerpt: "",
                        post_status: "publish",
                        comment_status: "closed",
                        ping_status: "closed",
                        post_password: "",
                        post_name: "yellow",
                        to_ping: "",
                        pinged: "",
                        post_modified: "2022-12-01 19:19:30",
                        post_modified_gmt: "2022-12-01 19:19:30",
                        post_content_filtered: "",
                        post_parent: 0,
                        guid: "https://ciy-companion.local/?post_type=color&#038;p=186",
                        menu_order: 0,
                        post_type: "color",
                        post_mime_type: "",
                        comment_count: "0",
                        filter: "raw",
                      },
                    ],
                  },
                  {
                    name: "Adult Leader Meeting",
                    location: "Lower Seeger",
                    icon: '<i class="fa-solid fa-file" aria-hidden="true"></i>',
                    time: "6:15 pm",
                    color: false,
                  },
                  {
                    name: "Student Only Session (Sit in Groups)",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-place-of-worship" aria-hidden="true"></i>',
                    time: "6:15 pm",
                    color: false,
                  },
                  {
                    name: "Intermission",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-crown" aria-hidden="true"></i>',
                    time: "7:15 pm",
                    color: false,
                  },
                  {
                    name: "Evening Session",
                    location: "Seeger Memorial Chapel",
                    icon: '<i class="fa-solid fa-place-of-worship" aria-hidden="true"></i>',
                    time: "7:30 pm",
                    color: false,
                  },
                  {
                    name: "Youth Group Time",
                    location: "",
                    icon: '<i class="fa-solid fa-square-question" aria-hidden="true"></i>',
                    time: "9:00 pm",
                    color: false,
                  },
                  {
                    name: "Late Night Hang ($1 Canteen)",
                    location: "",
                    icon: '<i class="fa-solid fa-crown" aria-hidden="true"></i>',
                    time: "",
                    color: false,
                  },
                  {
                    name: "Dorms",
                    location: "",
                    icon: '<i class="fa-solid fa-bed" aria-hidden="true"></i>',
                    time: "",
                    color: false,
                  },
                ],
              },
            ],
          },
          connect: { title: "", connections: false },
          video: { title: "", id: "" },
          image: { title: "Campus Map", image: false },
          grid: { title: "", description: "", images: false },
          app: {
            title: "",
            name: "",
            apple_store_url: "",
            google_play_store_url: "",
            description: "",
            icon: false,
          },
        },
      ],
      location: "Milligan University",
      start_date: "06/12/2024",
      end_date: "06/16/2024",
      coming_soon: false,
      coming_soon_data: { message: "", label: "", url: "" },
    },
  },
];
